@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "ROOT=%~dp0"
set "NINJA_DIR=%ROOT%build\ninja"
set "NINJA_FILE=%NINJA_DIR%\build.ninja"

if /I "%~1"=="--internal-build" (
    set "INTERNAL_TARGET=%~2"
    if /I "!INTERNAL_TARGET!"=="dml" goto :build_dml
    if /I "!INTERNAL_TARGET!"=="cuda" goto :build_cuda
    if /I "!INTERNAL_TARGET!"=="worker" goto :build_worker
    echo Unknown internal build target: !INTERNAL_TARGET!
    exit /b 2
)

set "TARGET=%~1"
if "%TARGET%"=="" set "TARGET=dml"

if /I "%TARGET%"=="help" goto :help
if /I "%TARGET%"=="-h" goto :help
if /I "%TARGET%"=="--help" goto :help

if /I "%TARGET%"=="generate" (
    call :write_ninja
    if errorlevel 1 exit /b !ERRORLEVEL!
    echo Wrote "%NINJA_FILE%"
    exit /b 0
)

set "NINJA_ARGS="
if "%TARGET:~0,1%"=="-" (
    set "NINJA_ARGS=%*"
    set "TARGET=dml"
) else (
    shift /1
    set "NINJA_ARGS=%*"
)

call :write_ninja
if errorlevel 1 exit /b !ERRORLEVEL!

call :find_ninja
if errorlevel 1 exit /b !ERRORLEVEL!

pushd "%ROOT%" >nul
"%NINJA_EXE%" -f "%NINJA_FILE%" %NINJA_ARGS% "%TARGET%"
set "BUILD_EXIT=%ERRORLEVEL%"
popd >nul
exit /b %BUILD_EXIT%

:help
echo Usage: build-ninja.bat [target] [ninja options]
echo.
echo Targets:
echo   dml       Build the DirectML application with 0BS_box_2.vcxproj. Default.
echo   cuda      Build the CUDA application via cuda\build-cuda.ps1.
echo   worker    Build the CUDA YOLO annotation worker via cuda\build-yolo-worker.ps1.
echo   all       Build dml, cuda, and worker through Ninja.
echo   generate  Write build\ninja\build.ninja without invoking Ninja.
echo.
echo Examples:
echo   build-ninja.bat
echo   build-ninja.bat cuda
echo   build-ninja.bat all -j 1
echo   build-ninja.bat dml -v
exit /b 0

:write_ninja
if not exist "%NINJA_DIR%" mkdir "%NINJA_DIR%"
if errorlevel 1 exit /b !ERRORLEVEL!

set "NINJA_TEMP=%NINJA_DIR%\build.%RANDOM%.%RANDOM%.ninja.tmp"
> "%NINJA_TEMP%" echo # Generated by build-ninja.bat. Edit the batch file, not this file.
>> "%NINJA_TEMP%" echo ninja_required_version = 1.10
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo pool msbuild_pool
>> "%NINJA_TEMP%" echo   depth = 1
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo rule run
>> "%NINJA_TEMP%" echo   command = $cmd
>> "%NINJA_TEMP%" echo   description = $desc
>> "%NINJA_TEMP%" echo   pool = msbuild_pool
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo build run_dml: run
>> "%NINJA_TEMP%" echo   cmd = cmd /d /c ""%ROOT%build-ninja.bat" --internal-build dml"
>> "%NINJA_TEMP%" echo   desc = Build 0BS DirectML
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo build run_cuda: run
>> "%NINJA_TEMP%" echo   cmd = cmd /d /c ""%ROOT%build-ninja.bat" --internal-build cuda"
>> "%NINJA_TEMP%" echo   desc = Build 0BS CUDA
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo build run_worker: run
>> "%NINJA_TEMP%" echo   cmd = cmd /d /c ""%ROOT%build-ninja.bat" --internal-build worker"
>> "%NINJA_TEMP%" echo   desc = Build YOLO annotation worker
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo build dml: phony run_dml
>> "%NINJA_TEMP%" echo build cuda: phony run_cuda
>> "%NINJA_TEMP%" echo build worker: phony run_worker
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo build all: phony dml cuda worker
>> "%NINJA_TEMP%" echo.
>> "%NINJA_TEMP%" echo default dml
move /y "%NINJA_TEMP%" "%NINJA_FILE%" >nul
if errorlevel 1 (
    set "MOVE_EXIT=!ERRORLEVEL!"
    del /q "%NINJA_TEMP%" >nul 2>nul
    exit /b !MOVE_EXIT!
)
exit /b 0

:find_ninja
if defined NINJA_EXE (
    if exist "%NINJA_EXE%" exit /b 0
)

for /f "delims=" %%I in ('where ninja.exe 2^>nul') do (
    set "NINJA_EXE=%%I"
    exit /b 0
)

set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if exist "%VSWHERE%" (
    for /f "usebackq delims=" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.CMake.Project -find Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe`) do (
        if exist "%%I" (
            set "NINJA_EXE=%%I"
            exit /b 0
        )
    )
)

for %%I in (
    "%ProgramFiles%\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
    "%ProgramFiles%\Microsoft Visual Studio\18\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
    "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
    "%ProgramFiles%\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
) do (
    if exist "%%~I" (
        set "NINJA_EXE=%%~I"
        exit /b 0
    )
)

echo ninja.exe was not found. Install Ninja or set NINJA_EXE to the full ninja.exe path.
exit /b 1

:setup_vs
if defined VSDEVCMD (
    if exist "%VSDEVCMD%" goto :call_vsdevcmd
)

set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if exist "%VSWHERE%" (
    for /f "usebackq delims=" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find Common7\Tools\VsDevCmd.bat`) do (
        if exist "%%I" (
            set "VSDEVCMD=%%I"
            goto :call_vsdevcmd
        )
    )
)

for %%I in (
    "%ProgramFiles%\Microsoft Visual Studio\18\Community\Common7\Tools\VsDevCmd.bat"
    "%ProgramFiles%\Microsoft Visual Studio\18\BuildTools\Common7\Tools\VsDevCmd.bat"
    "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
    "%ProgramFiles%\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
) do (
    if exist "%%~I" (
        set "VSDEVCMD=%%~I"
        goto :call_vsdevcmd
    )
)

echo VsDevCmd.bat was not found. Install Visual Studio C++ tools or set VSDEVCMD.
exit /b 1

:call_vsdevcmd
call "%VSDEVCMD%" -arch=x64 -host_arch=x64 >nul
if errorlevel 1 exit /b !ERRORLEVEL!

if defined MSBUILD_EXE (
    if exist "%MSBUILD_EXE%" exit /b 0
)

for /f "delims=" %%I in ('where MSBuild.exe 2^>nul') do (
    set "MSBUILD_EXE=%%I"
    exit /b 0
)

for %%I in (
    "%ProgramFiles%\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe"
    "%ProgramFiles%\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
    "%ProgramFiles%\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
    "%ProgramFiles%\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
) do (
    if exist "%%~I" (
        set "MSBUILD_EXE=%%~I"
        exit /b 0
    )
)

echo MSBuild.exe was not found after Visual Studio environment setup.
exit /b 1

:build_dml
call :setup_vs
if errorlevel 1 exit /b !ERRORLEVEL!

echo Building DirectML application...
"%MSBUILD_EXE%" "%ROOT%0BS_box_2.vcxproj" /p:Configuration=DML /p:Platform=x64 /m /v:minimal
exit /b !ERRORLEVEL!

:build_cuda
echo Building CUDA application...
powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%cuda\build-cuda.ps1"
exit /b !ERRORLEVEL!

:build_worker
echo Building CUDA YOLO annotation worker...
powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%cuda\build-yolo-worker.ps1"
exit /b !ERRORLEVEL!
